/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from '../routes/__root'
import { Route as SiteRouteImport } from '../routes/_site'
import { Route as SiteIndexRouteImport } from '../routes/_site/index'
import { Route as SiteContatoRouteImport } from '../routes/_site/contato'
import { Route as SiteDuvidasRouteImport } from '../routes/_site/duvidas'
import { Route as SiteGaleriasRouteImport } from '../routes/_site/galerias'
import { Route as SiteHomeRouteImport } from '../routes/_site/home'
import { Route as SitePoliticasIndexRouteImport } from '../routes/_site/politicas/index'
import { Route as SitePoliticasSlugRouteImport } from '../routes/_site/politicas/$slug'
import { Route as SiteServicosIndexRouteImport } from '../routes/_site/servicos/index'
import { Route as SiteServicosSlugRouteImport } from '../routes/_site/servicos/$slug'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContatoRoute = SiteContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDuvidasRoute = SiteDuvidasRouteImport.update({
  id: '/duvidas',
  path: '/duvidas',
  getParentRoute: () => SiteRoute,
} as any)
const SiteGaleriasRoute = SiteGaleriasRouteImport.update({
  id: '/galerias',
  path: '/galerias',
  getParentRoute: () => SiteRoute,
} as any)
const SiteHomeRoute = SiteHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => SiteRoute,
} as any)
const SitePoliticasIndexRoute = SitePoliticasIndexRouteImport.update({
  id: '/politicas/',
  path: '/politicas/',
  getParentRoute: () => SiteRoute,
} as any)
const SitePoliticasSlugRoute = SitePoliticasSlugRouteImport.update({
  id: '/politicas/$slug',
  path: '/politicas/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicosIndexRoute = SiteServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicosSlugRoute = SiteServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/contato': typeof SiteContatoRoute
  '/duvidas': typeof SiteDuvidasRoute
  '/galerias': typeof SiteGaleriasRoute
  '/home': typeof SiteHomeRoute
  '/politicas/$slug': typeof SitePoliticasSlugRoute
  '/servicos/$slug': typeof SiteServicosSlugRoute
  '/politicas/': typeof SitePoliticasIndexRoute
  '/servicos/': typeof SiteServicosIndexRoute
}
export interface FileRoutesByTo {
  '/contato': typeof SiteContatoRoute
  '/duvidas': typeof SiteDuvidasRoute
  '/galerias': typeof SiteGaleriasRoute
  '/home': typeof SiteHomeRoute
  '/': typeof SiteIndexRoute
  '/politicas/$slug': typeof SitePoliticasSlugRoute
  '/servicos/$slug': typeof SiteServicosSlugRoute
  '/politicas': typeof SitePoliticasIndexRoute
  '/servicos': typeof SiteServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/contato': typeof SiteContatoRoute
  '/_site/duvidas': typeof SiteDuvidasRoute
  '/_site/galerias': typeof SiteGaleriasRoute
  '/_site/home': typeof SiteHomeRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/politicas/$slug': typeof SitePoliticasSlugRoute
  '/_site/servicos/$slug': typeof SiteServicosSlugRoute
  '/_site/politicas/': typeof SitePoliticasIndexRoute
  '/_site/servicos/': typeof SiteServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/duvidas'
    | '/galerias'
    | '/home'
    | '/politicas/$slug'
    | '/servicos/$slug'
    | '/politicas/'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contato'
    | '/duvidas'
    | '/galerias'
    | '/home'
    | '/'
    | '/politicas/$slug'
    | '/servicos/$slug'
    | '/politicas'
    | '/servicos'
  id:
    | '__root__'
    | '/_site'
    | '/_site/contato'
    | '/_site/duvidas'
    | '/_site/galerias'
    | '/_site/home'
    | '/_site/'
    | '/_site/politicas/$slug'
    | '/_site/servicos/$slug'
    | '/_site/politicas/'
    | '/_site/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contato': {
      id: '/_site/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof SiteContatoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/duvidas': {
      id: '/_site/duvidas'
      path: '/duvidas'
      fullPath: '/duvidas'
      preLoaderRoute: typeof SiteDuvidasRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/galerias': {
      id: '/_site/galerias'
      path: '/galerias'
      fullPath: '/galerias'
      preLoaderRoute: typeof SiteGaleriasRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/home': {
      id: '/_site/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof SiteHomeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/politicas/': {
      id: '/_site/politicas/'
      path: '/politicas'
      fullPath: '/politicas/'
      preLoaderRoute: typeof SitePoliticasIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/politicas/$slug': {
      id: '/_site/politicas/$slug'
      path: '/politicas/$slug'
      fullPath: '/politicas/$slug'
      preLoaderRoute: typeof SitePoliticasSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/servicos/': {
      id: '/_site/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof SiteServicosIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/servicos/$slug': {
      id: '/_site/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof SiteServicosSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteContatoRoute: typeof SiteContatoRoute
  SiteDuvidasRoute: typeof SiteDuvidasRoute
  SiteGaleriasRoute: typeof SiteGaleriasRoute
  SiteHomeRoute: typeof SiteHomeRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SitePoliticasSlugRoute: typeof SitePoliticasSlugRoute
  SiteServicosSlugRoute: typeof SiteServicosSlugRoute
  SitePoliticasIndexRoute: typeof SitePoliticasIndexRoute
  SiteServicosIndexRoute: typeof SiteServicosIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContatoRoute: SiteContatoRoute,
  SiteDuvidasRoute: SiteDuvidasRoute,
  SiteGaleriasRoute: SiteGaleriasRoute,
  SiteHomeRoute: SiteHomeRoute,
  SiteIndexRoute: SiteIndexRoute,
  SitePoliticasSlugRoute: SitePoliticasSlugRoute,
  SiteServicosSlugRoute: SiteServicosSlugRoute,
  SitePoliticasIndexRoute: SitePoliticasIndexRoute,
  SiteServicosIndexRoute: SiteServicosIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
